apiVersion: v1
kind: Service
metadata:
  name: flaskapp-service
  labels:
    app: flaskapp
spec:
  ports:
    - port: 80
      targetPort: 5000
  selector:
    app: flaskapp
    tier: frontend
  type: LoadBalancer
---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: efs-sc
provisioner: efs.csi.aws.com
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: flaskapp-efs-pv
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: efs-sc
  csi:
    driver: efs.csi.aws.com
    volumeHandle: fs-0414d36c9ee3f4bef
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: flaskapp-efs-pvc
  labels:
    app: flaskapp
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: efs-sc
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flaskapp-deployment
  labels:
    app: flaskapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flaskapp
      tier: frontend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: flaskapp
        tier: frontend
    spec:
      containers:
      - name: flaskapp
        image: pocverdn/bookstore:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
          name: http
        volumeMounts:
        - name: flaskapp-persistent-storage
          mountPath: /app/data
      
      volumes:
      - name: flaskapp-persistent-storage
        persistentVolumeClaim:
          claimName: flaskapp-efs-pvc
